### ISSUE TITLE
Objects going out of scope

### ISSUE THREAD

**Issue by rith87** [CoSys-Lab/dash7-ap-open-source-stack#8]
There are some places in the code where an object is declared on the stack in a function, passed into some struct as some pointer and then the object goes out of scope. Isn't this rather dangerous since the object goes out of scope?

For example, in trans.c

```c
static void nwl_rx_callback(nwl_rx_res_t* result)
{
...
	case D7AQP_COMMAND_TYPE_NA2P_REQUEST:
	{
		switch (query_result.d7aqp_command.command_code & 0x0F)
		{
			case D7AQP_OPCODE_ANNOUNCEMENT_FILE:
			{
				D7AQP_Single_File_Return_Template sfr_tmpl;
				sfr_tmpl.return_file_id = data->payload[pointer++];
				sfr_tmpl.file_offset = data->payload[pointer++];
				sfr_tmpl.isfb_total_length = data->payload[pointer++];
				sfr_tmpl.file_data = &data->payload[pointer];

				pointer += sfr_tmpl.isfb_total_length - sfr_tmpl.file_offset;

				query_result.d7aqp_command.command_data = &sfr_tmpl;
			}
		}
		break;
	}
...
	trans_rx_query_callback(&query_result);
...
}
```

So, in the above case, ```sfr_tmpl``` goes out of scope outside of the switch and then the callback is called. Am I making sense here? Or is there something I don't know about MSP430 programming?

**Comment by glennergeerts** [comment]
not relevant anymore after rewrite, closing for now
