### ISSUE TITLE
Request response example

### ISSUE THREAD

**Issue by rith87** [CoSys-Lab/dash7-ap-open-source-stack#9]
In the example, I've observed that the requester receives a response from the responder but the response is empty (all 0's). I dug into it a little bit and noticed that ```trans_tx_query``` is not consuming the payload in the file template.

```c
void trans_tx_query(D7AQP_Command* command, uint8_t subnet, uint8_t spectrum_id, int8_t tx_eirp)
{
...
	switch (command->command_code & 0x70)
	{
		// Response
		case D7AQP_COMMAND_TYPE_RESPONSE:
		{
			switch (command->command_code & 0x0F)
			{
				case D7AQP_OPCODE_ANNOUNCEMENT_FILE:
				{
					break;
				}
			}
			break;
		}
...
}
```

The same behavior happens on the rx side as well. Or am I misunderstanding the code?

**Comment by glennergeerts** [comment]
not relevant anymore after rewrite, closing for now
